QuanLyNhaHang/Models/MonAn.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuanLyNhaHang.Models
{
    public class MonAn
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string TenMon { get; set; }
        public decimal DonGia { get; set; }
        public string HinhAnh { get; set; }
        public ICollection<ThucDon> ThucDons { get; set; }
        public ICollection<HoaDonChiTiet> HoaDons { get; set; }
    }
}

QuanLyNhaHang/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyNhaHang.Models;
using QuanLyNhaHang.View_Model;

namespace QuanLyNhaHang.Controllers
{
    public class HoaDonsController : Controller
    {
        private QuanLyNhaHangContext db = new QuanLyNhaHangContext();

        // GET: HoaDons
        public async Task<ActionResult> Index()
        {
            return View(await db.HoaDons.ToListAsync());
        }

        // GET: HoaDons/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<HoaDonChiTietVM> hoaDonChiTietVMs = new List<HoaDonChiTietVM>();
            HoaDon hoaDon = await db.HoaDons.FindAsync(id);
            var details = hoaDon.HoaDonChiTiets;
            foreach (var item in details)
            {
                HoaDonChiTietVM hoaDonChiTietVM = new HoaDonChiTietVM();
                hoaDonChiTietVM.Id = item.Id;
                hoaDonChiTietVM.MonAnId = item.MonAnId;
                hoaDonChiTietVM.TenMon = item.MonAn.TenMon;
                hoaDonChiTietVM.DonGia = item.MonAn.DonGia;
                hoaDonChiTietVM.SL = item.SL;
                hoaDonChiTietVM.ThanhTien = item.ThanhTien;
                hoaDonChiTietVMs.Add(hoaDonChiTietVM);
            }

            HoaDonVM hoaDonVM = new HoaDonVM();
            hoaDonVM.MaBan = hoaDon.MaBan;
            hoaDonVM.isPaid = hoaDon.IsPaid;
            hoaDonVM.GioBatDau = hoaDon.GioBatDau;
            hoaDonVM.GioKetThuc = hoaDon.GioKetThuc;
            hoaDonVM.TongTien = hoaDon.TongTien;
            hoaDonVM.HoaDonChiTietVM = hoaDonChiTietVMs;

            return View(hoaDonVM);
        }

        // GET: HoaDons/Create
        public ActionResult Create()
        {
            var lstDishes = TempData["listMonAn"] as List<MonAn>;
            HoaDonVM hoaDonVM = new HoaDonVM();
            List<HoaDonChiTietVM> hoaDonChiTietVMs = new List<HoaDonChiTietVM>();
            for (int i = 0; i < lstDishes.Count(); i++)
            {
                var check = hoaDonChiTietVMs.Where(x => x.MonAnId == lstDishes[i].Id).SingleOrDefault();
                if (check == null)
                {
                    HoaDonChiTietVM hoaDonChiTietVM = new HoaDonChiTietVM();
                    hoaDonChiTietVM.TenMon = lstDishes[i].TenMon;
                    hoaDonChiTietVM.DonGia = lstDishes[i].DonGia;
                    hoaDonChiTietVM.SL = 1;
                    hoaDonChiTietVM.ThanhTien = lstDishes[i].DonGia;
                    hoaDonChiTietVMs.Add(hoaDonChiTietVM);
                }
                else
                {
                    var alreadyhavedish = hoaDonChiTietVMs.Where(x => x.Id == lstDishes[i].Id).FirstOrDefault();
                    alreadyhavedish.SL += 1;
                    alreadyhavedish.ThanhTien += alreadyhavedish.DonGia;
                }
            }

            hoaDonVM.GioBatDau = DateTime.Now;
            hoaDonVM.TongTien = lstDishes.Sum(x => x.DonGia);
            hoaDonVM.HoaDonChiTietVM = hoaDonChiTietVMs;
            TempData.Keep("listMonAn");

            return View(hoaDonVM);
        }

        // POST: HoaDons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,MaBan,TongTien,GioBatDau,IsPaid,HoaDonChiTiets")] HoaDon hoaDon)
        {
            try
            {
                var lstDishes = TempData["listMonAn"] as List<MonAn>;
                List<HoaDonChiTiet> lstdetail = new List<HoaDonChiTiet>();
                foreach(var item in lstDishes)
                {
                    var check = lstdetail.Where(x => x.MonAnId == item.Id).FirstOrDefault();
                    if(check == null)
                    {
                        HoaDonChiTiet detail = new HoaDonChiTiet();
                        detail.HoaDonId = hoaDon.Id;
                        detail.MonAnId = item.Id;
                        detail.SL = 1;
                        detail.ThanhTien = item.DonGia;
                        lstdetail.Add(detail);
                    }
                    else
                    {
                        var alreadyhave = lstdetail.Where(x => x.MonAnId == item.Id).FirstOrDefault();
                        alreadyhave.SL += 1;
                        alreadyhave.ThanhTien += item.DonGia;
                    }
                }

                hoaDon.HoaDonChiTiets = lstdetail;

                if(ModelState.IsValid)
                {
                    db.HoaDons.Add(hoaDon);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }

                
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "tạm thời không thể lưu! thử lại sau");
            }

            return View(hoaDon);
        }

        // GET: HoaDons/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            { 
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = await db.HoaDons.FindAsync(id);
            var detail = hoaDon.HoaDonChiTiets.ToList();
            HoaDonVM bill = new HoaDonVM();
            List<HoaDonChiTietVM> detailbill = new List<HoaDonChiTietVM>();
            foreach(var item in detail)
            {
                HoaDonChiTietVM detailVM = new HoaDonChiTietVM();
                detailVM.Id = item.Id;
                detailVM.MonAnId = item.MonAnId;
                detailVM.TenMon = item.MonAn.TenMon;
                detailVM.DonGia = item.MonAn.DonGia;
                detailVM.SL = item.SL;
                detailVM.ThanhTien = item.ThanhTien;
                detailbill.Add(detailVM);
            }

            bill.Id = hoaDon.Id;
            bill.GioBatDau = hoaDon.GioBatDau;
            bill.isPaid = hoaDon.IsPaid;
            bill.TongTien = hoaDon.TongTien;
            bill.GioKetThuc = DateTime.Now;
            bill.HoaDonChiTietVM = detailbill;
            bill.MaBan = hoaDon.MaBan;

            if (hoaDon == null)
            {
                return HttpNotFound(); 
            }
            return View(bill);
        }

        // POST: HoaDons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,MaBan,TongTien,GioBatDau,GioKetThuc,IsPaid")] HoaDon hoaDon)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(hoaDon).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "Tạm thời không thể lưu! Thử lại sau");
            }
            
            return View(hoaDon);
        }

        // GET: HoaDons/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = await db.HoaDons.FindAsync(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // POST: HoaDons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                HoaDon hoaDon = await db.HoaDons.FindAsync(id);
                db.HoaDons.Remove(hoaDon);
                await db.SaveChangesAsync();
            }
            catch(DataException)
            {
                ModelState.AddModelError("","Tạm thời không thể xóa!");
            }
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ListDaChon()
        {

            return View();

        }
    }
}

QuanLyNhaHang/Controllers/MonAnsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyNhaHang.Models;

namespace QuanLyNhaHang.Controllers
{
    public class MonAnsController : Controller
    {
        private QuanLyNhaHangContext db = new QuanLyNhaHangContext();

        // GET: MonAns
        public async Task<ActionResult> Index()
        {
            return View(await db.MonAns.ToListAsync());
        }

        // GET: MonAns/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = await db.MonAns.FindAsync(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            return View(monAn);
        }

        // GET: MonAns/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MonAns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,TenMon,Gia")] MonAn monAn)
        {
            if (ModelState.IsValid)
            {
                db.MonAns.Add(monAn);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(monAn);
        }

        // GET: MonAns/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = await db.MonAns.FindAsync(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            return View(monAn);
        }

        // POST: MonAns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,TenMon,Gia")] MonAn monAn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monAn).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(monAn);
        }

        // GET: MonAns/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = await db.MonAns.FindAsync(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            return View(monAn);
        }

        // POST: MonAns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            MonAn monAn = await db.MonAns.FindAsync(id);
            db.MonAns.Remove(monAn);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult DatMon()
        {
            var currentDay = DateTime.Now.DayOfWeek;
            var Menu = db.ThucDons.FirstOrDefault(x=>x.DayOfWeek == currentDay);
            if(Menu != null)
            {
                var MenuDetail = Menu.ThucDonChiTiets;
                return View(MenuDetail);
            }
            else
            {
                ViewBag.Message = "Hôm nay không có món nào hết";
            }
            return View();
        }

        public JsonResult ListMonChon(int MonAnID, bool isAdd, int sl)
        {
            //khởi tạo object
            List<MonAn> listMonAn = new List<MonAn>();
            //check session đã được tạo hay chưa
            if (TempData.ContainsKey("listMonAn"))
                //session đã đc tạo
                listMonAn = TempData["listMonAn"] as List<MonAn>;
            //lấy ra Món ăn đang được thao tác
            var monAn = db.MonAns.FirstOrDefault(x => x.Id == MonAnID);
           

            if (isAdd)
            {
                for (int i = 0; i < sl; i++)
                {

                    //trường hợp thêm mới món ăn
                    listMonAn.Add(monAn);
                }
            }
            else
            {
                var slma = listMonAn.Where(x => x.Id == MonAnID).Count();

                if (slma == 0)
                {
                    return Json(new { Message = "bạn chưa chọn món ăn" }, JsonRequestBehavior.AllowGet);
                }
                if (slma >=sl)
                {
                    for(int i=0; i < sl; i++)
                    {
                        //trường hợp xóa món ăn
                        listMonAn.Remove(listMonAn.FirstOrDefault(x => x.Id == MonAnID));
                        slma = listMonAn.Count();
                    }
                }
                else
                {
                    return Json(new { Message = "Xóa lớn hơn số lượng hiện có" }, JsonRequestBehavior.AllowGet);
                }
                
            }
            TempData["listMonAn"] = listMonAn;
            return Json(new { Message = "Thành Công" }, JsonRequestBehavior.AllowGet);
        }

        

    }
}

QuanLyNhaHang/Views/MonAns/Create.cshtml
@model QuanLyNhaHang.Models.MonAn

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MonAn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenMon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyNhaHang/Views/MonAns/DatMon.cshtml
@model IEnumerable<QuanLyNhaHang.Models.MonAn>
@{
    ViewBag.Title = "DatMon";
    var stt = 1;
}

<h2>DatMon</h2>

<div class="container">
    <table class="table">
        <tr>
            <th>STT</th>
            <th>Tên món</th>
            <th>Hình ảnh</th>
            <th>Giá</th>
            <th>Số lượng</th>
            <th>Hành động</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@stt</td>
                <td>@item.TenMon</td>
                <td><img src="@item.HinhAnh" , class="glyphicon-picture" /></td>
                <td>@item.Gia</td>
                <td><input type="text" id="SL_@item.Id" /></td>
                <td>
                    <button onclick="ThemMonAn(@item.Id)" , class="drp-buttons">Add</button>
                    <button onclick="XoaMonAn(@item.Id)" , class="drp-buttons">Remove</button>
                </td>
            </tr>
            stt++;
        }
    </table>

    <br />
    <div>
        <a href="@Url.Action("Create","HoaDons")" class="text-right">Thanh toán</a>
    </div>
    


</div>



<script>
    function ThemMonAn(MonAnID) {
       
        var _sl = document.getElementById("SL_" + MonAnID).value;
        $.ajax({
            url: '@Url.Action("ListMonChon", "MonAns")',
            method: "GET",
            data: { MonAnID: MonAnID, isAdd: true, sl: _sl },
            success: function (data) {
                console.log(data);
                alert(data.Message)
            },
            error: function (xhr) {
                alert('error');
            }
        });
    }

    function XoaMonAn(MonAnID) {

        var _sl = document.getElementById("SL_" + MonAnID).value;
        $.ajax({
            url: '@Url.Action("ListMonChon", "MonAns")',
            method: "GET",
            data: { MonAnID: MonAnID, isAdd: false, sl: _sl },
            success: function (data) {
                console.log(data);
                alert(data.Message)
            },
            error: function (xhr) {
                alert('error');
            }
        });
    }
</script>

QuanLyNhaHang/Views/MonAns/Delete.cshtml
@model QuanLyNhaHang.Models.MonAn

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonAn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenMon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuanLyNhaHang/Views/MonAns/Details.cshtml
@model QuanLyNhaHang.Models.MonAn

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MonAn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenMon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QuanLyNhaHang/Views/MonAns/Edit.cshtml
@model QuanLyNhaHang.Models.MonAn

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MonAn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TenMon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLyNhaHang/Views/MonAns/Index.cshtml
@model IEnumerable<QuanLyNhaHang.Models.MonAn>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenMon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenMon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>